//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "rooms")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::rooms_users::Entity")]
    RoomsUsers,
}

impl Related<super::rooms_users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RoomsUsers.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
