//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

// @todo how can we keep this and how this deserialize and serialze work
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Deserialize, Serialize)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::messages::Entity")]
    Messages,
    #[sea_orm(has_many = "super::rooms_users::Entity")]
    RoomsUsers,
}

impl Related<super::messages::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Messages.def()
    }
}

impl Related<super::rooms_users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RoomsUsers.def()
    }
}

impl Related<super::rooms::Entity> for Entity {
    fn to() -> RelationDef {
        super::rooms_users::Relation::Rooms.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::rooms_users::Relation::Users.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
